import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/global/Navbar";
import Footer from "../components/global/Footer";
// import Header from "../components/global/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airprax Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="lg:mt-[96px] mt-[60px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
